services:
  - type: web
    name: cronograma
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn gestion_activos.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - fromGroup: env
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: cronograma_db
          property: connectionString

databases:
  - name: cronograma_db
    plan: free
